-- Seed countries for the conflict form (H2 in-memory DB)
INSERT INTO countries (name, code) VALUES ('United States', 'US');
INSERT INTO countries (name, code) VALUES ('Canada', 'CA');
INSERT INTO countries (name, code) VALUES ('Mexico', 'MX');
INSERT INTO countries (name, code) VALUES ('Brazil', 'BR');
INSERT INTO countries (name, code) VALUES ('Argentina', 'AR');
INSERT INTO countries (name, code) VALUES ('United Kingdom', 'GB');
INSERT INTO countries (name, code) VALUES ('France', 'FR');
INSERT INTO countries (name, code) VALUES ('Germany', 'DE');
INSERT INTO countries (name, code) VALUES ('Spain', 'ES');
INSERT INTO countries (name, code) VALUES ('Italy', 'IT');
INSERT INTO countries (name, code) VALUES ('Ukraine', 'UA');
INSERT INTO countries (name, code) VALUES ('Russia', 'RU');
INSERT INTO countries (name, code) VALUES ('Turkey', 'TR');
INSERT INTO countries (name, code) VALUES ('Egypt', 'EG');
INSERT INTO countries (name, code) VALUES ('South Africa', 'ZA');
INSERT INTO countries (name, code) VALUES ('India', 'IN');
INSERT INTO countries (name, code) VALUES ('Pakistan', 'PK');
INSERT INTO countries (name, code) VALUES ('China', 'CN');
INSERT INTO countries (name, code) VALUES ('Japan', 'JP');
INSERT INTO countries (name, code) VALUES ('South Korea', 'KR');
INSERT INTO countries (name, code) VALUES ('Australia', 'AU');
INSERT INTO countries (name, code) VALUES ('New Zealand', 'NZ');
INSERT INTO countries (name, code) VALUES ('Indonesia', 'ID');
INSERT INTO countries (name, code) VALUES ('Thailand', 'TH');
INSERT INTO countries (name, code) VALUES ('Vietnam', 'VN');
INSERT INTO countries (name, code) VALUES ('Saudi Arabia', 'SA');
INSERT INTO countries (name, code) VALUES ('Iran', 'IR');
INSERT INTO countries (name, code) VALUES ('Israel', 'IL');
